### ISSUE TITLE
An idea

### ISSUE THREAD

**Issue by Lucy-2077** [PRO100KatYT/SaveTheWorldClaimer#11]
Hello , I have an idea , is possible to make an option for discord webhook when updating in the script ( exemple : when reward is claimed etc.. ) 
This can be cool c:
Thank you for this tool c:

**Comment by bns34** [comment]
@PRO100KatYT if you cant get this done I can PR if you would like

**Comment by PRO100KatYT** [comment]
At the moment I don't have any plans to add this feature.
I might look into this in the future.
