### ISSUE TITLE
can u add webhook ?

### ISSUE THREAD

**Issue by darzex** [PRO100KatYT/SaveTheWorldClaimer#23]
can u add webhook ? so we know if it bug or just to know when not at home or something ty

**Comment by bns34** [comment]
This is already present in PR #12.

The PR however hasn't been merged so the PR is available in [my fork](https://github.com/Salty-Coder/SaveTheWorldClaimer).

**Comment by darzex** [comment]
> This is already present in PR #12.
> 
> The PR however hasn't been merged so the PR is available in [my fork](https://github.com/Salty-Coder/SaveTheWorldClaimer).

Yes but its an olf version that why i asked 👍

**Comment by bns34** [comment]
@darzex I have updated my fork, it should all work incase you want to check it out.

**Comment by darzex** [comment]
Thanks you👍
 i will try it tommorow

**Comment by darzex** [comment]
hi i have a bug ? 
![image](https://user-images.githubusercontent.com/78509328/216699698-d3c02682-1dcf-4b7c-a7a9-4e1a7b169888.png)

**Comment by bns34** [comment]
I've just pushed an update that should fix it. Sorry about that.

**Comment by PRO100KatYT** [comment]
👀

**Comment by PRO100KatYT** [comment]
Introduced in v1.13.0 Update.
