### ISSUE TITLE
Daily quests replace

### ISSUE THREAD

**Issue by zdky** [PRO100KatYT/SaveTheWorldClaimer#25]
Is it possible to add a replacement daily quests?

**Comment by bns34** [comment]
@PRO100KatYT correct me if i'm wrong but I assume this wouldn't be possible.
Daily quests aren't just things you can claim, you need to actually complete the challenge.
Even if it was possible to just *claim* a daily quest reward, it would most likely get your account terminated.

**Comment by zdky** [comment]
No, in the quest log you can replace the daily quest with a new one.

**Comment by bns34** [comment]
Ah. Sorry I misunderstood what you meant. I assume this would be possible and PRO100KatYT might implement it at some point in the future.
However, if your playing the game to complete the quests, why not replace the quest manually on the game?

**Comment by zdky** [comment]
Well, for example, I can't get into the game some days, but I could change the quests to simpler ones.

**Comment by bns34** [comment]
I don't quite understand...
Why would you want to replace daily quests if you cant do the daily quests?

**Comment by zdky** [comment]
Just lazy to go into the game to change the quest. I wait until I accumulate three quests and do them.

**Comment by bns34** [comment]
Ah. Do daily quests not reset each day?
I've never actually done a daily quest since buying stw in 2018

**Comment by PRO100KatYT** [comment]
If I find a good way to implement this to the program then I'll add it.

**Comment by zdky** [comment]
they are added every day, and they can be replaced by a random new one. there is also a limit of 3 daily quests in the quest log, which do not disappear anywhere.

**Comment by bns34** [comment]
> they are added every day, and they can be replaced by a random new one. there is also a limit of 3 daily quests in the quest log, which do not disappear anywhere.

but if you don't complete them that day, do they reroll or remain the same the next day?

**Comment by zdky** [comment]
remain

**Comment by bns34** [comment]
> remain

Ah. I didn't know that. Thanks

**Comment by zdky** [comment]
I'm not sure, but I think it's always been like that.

**Comment by zdky** [comment]
> If I find a good way to implement this to the program then I'll add it.

How do you track game requests to the api? I could try to do it myself.

**Comment by bns34** [comment]
I believe it would be somewhat complex to implement. 
You would need to somehow get the ID of the quest, then make a request to replace the quest with that ID.

**Comment by PRO100KatYT** [comment]
> I believe it would be somewhat complex to implement. 
> You would need to somehow get the ID of the quest, then make a request to replace the quest with that ID.

I know how to implement that but the problem is that the main program can be ran in a loop and I wouldn't want to break that loop. Maybe I'll do it in a similar way I did the account manager (in the Main Menu). Expect the update within the next few days.

**Comment by PRO100KatYT** [comment]
Added in the 1.12.0 Update.
