### ISSUE TITLE
Add the possibility to create a http server

### ISSUE THREAD

**Issue by Mrgaton** [PRO100KatYT/SaveTheWorldClaimer#26]
It would be nice if you could turn on an http server even though it always returns a message to be able to host it from replit 24/7

**Comment by Mrgaton** [comment]
and a option to automatcly run the daily claimer when the program runs

**Comment by PRO100KatYT** [comment]
The option to automatically run the daily claimer when the program runs is already available by setting the value of `Skip_Main_Menu` in the config to `true`. In regards to the http server, I don't plan on adding it anytime soon.
