### ISSUE TITLE
Consider using refresh tokens instead of device auths

### ISSUE THREAD

**Issue by Not-Bay** [PRO100KatYT/SaveTheWorldClaimer#3]
It is known that using device auth is very convenient. But it can cause password resets

Consider using refresh tokens to avoid password resets, specifically using `launcherAppClient2`
The refresh tokens you generate with that client expire after 1987200 seconds (23 days)

**Comment by PRO100KatYT** [comment]
Thanks for letting me know about this. I think I will add an option to choose an auth method to the program's config file soon.

**Comment by PRO100KatYT** [comment]
The refresh token seems to expire when used. Is this token supposed to work this way?

**Comment by Not-Bay** [comment]
Of course it will expire, when you use that refresh token you will get a new auth data (new access token and new refresh token)

It would only be necessary to save the new refresh token (after using the old one).
I'm not sure if the launcher client can use the game endpoints but you could make it work like this:

Authenticate with authorization code (using the launcher client) and save the generated refresh token.
`https://www.epicgames.com/id/api/redirect?clientId=34a02cf8f4414e29b15921876da36f9a&responseType=code`
Then if you need to use the fortnite endpoints you authenticate with the refresh token and generate an exchange code to use with another fortnite client. Before generating exchange code make sure you save the new refresh token

The epic games launcher keeps the login active like this

**Comment by PRO100KatYT** [comment]
Ok, thanks

**Comment by PRO100KatYT** [comment]
Added it.
