### ISSUE TITLE
Research point claim problem

### ISSUE THREAD

**Issue by Mrgaton** [PRO100KatYT/SaveTheWorldClaimer#30]
I think he doesn't claim the research points well because he had plenty of points to redeem some and it doesn't matter that he runs the program because he didn't spend them on anything when he had it at lowest

**Comment by Playeereq** [comment]
?

**Comment by PRO100KatYT** [comment]
Could you give more details and information about this issue?

**Comment by Mrgaton** [comment]
The research point claimer works, but not the thing that levels up the things

**Comment by PRO100KatYT** [comment]
I just tested the `everyten` method of claiming the research points, and it worked for me. What research point claiming method do you use? Soon, I'll test the `lowest` method.

**Comment by Mrgaton** [comment]
What i use is the lowest.

**Comment by PRO100KatYT** [comment]
The `lowest` method also works for me.

**Comment by Mrgaton** [comment]
Sorry I need to make more tests and I don't have the time
