### ISSUE TITLE
Missing module 

### ISSUE THREAD

**Issue by R-Kurumi** [PRO100KatYT/SaveTheWorldClaimer#31]
In line 14 it will give an error saying that it didn't find "requests" 
![image 1](https://github.com/PRO100KatYT/SaveTheWorldClaimer/assets/157297977/f5d59590-21b7-4b6f-a67f-9cf7523467a7)

**Comment by Playeereq** [comment]
pip install requests

**Comment by PRO100KatYT** [comment]
Thank you for reaching out! It seems that you’re encountering an issue related to a missing Python module. Specifically, you’re trying to use the requests module, but it’s not found in your environment. Make sure that you have the requests module installed. If not, you can install it using the following command:
`python -m pip install requests`
This command will download and install the requests package, allowing you to use it in this Python code.
