### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by xxxnathan0463** [PRO100KatYT/SaveTheWorldClaimer#6]
hi sorry to disturb you but I have a little problem when I throw the py I show you a picture
![Capture d’écran (88)](https://user-images.githubusercontent.com/98721602/151727925-afa24907-7318-4aee-8eb2-9f9f2276a0b6.png)

**Comment by bns34** [comment]
pip install requests

**Comment by PRO100KatYT** [comment]
Just like @Salty-Coder said, you have to install the requests module by using the pip install requests command in the Windows Command Prompt.
